version: "3.3"

networks:
  answeroom_default:
    external: true

services:

  postgres:
    image: postgres:14.0
    container_name: answeroom_postgres
    restart: unless-stopped
    command: postgres -c 'max_connections=200'
    networks:
      - answeroom_default
    ports:
      - "12432:5432"
    environment:
      POSTGRES_PASSWORD: "111"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
